services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: employeedb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A employee_management worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    command: celery -A employee_management beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
